### ISSUE TITLE
Picker search icon not aligned and title attrs contain duplicate word

### ISSUE THREAD

**Issue by braksator** [micc83/fontIconPicker#25]
These aren't really a big deal, I fixed the first one with CSS, and just ignore the second thing.
I took a screenshot though to give some feedback, it's at the link below.
http://imgur.com/FUrq69w

**Comment by braksator** [comment]
I realise now that the first word is the title of the icon.  My users may not understand that though.  Could it be separated with a dash or something?

**Comment by micc83** [comment]
Hi, @braksator thank you for your feedback. Unfortunately since version 2 of fontIconPicker was the result of a collaboration with another person, which is not in the project anymore, I cannot possibly keep addressing issues related with all the features that this third person added to the project. Hopefully someone else will step in.

Cheers,
Alex

**Comment by braksator** [comment]
The issue with title attrs is my fault.  I am providing this info to the plugin, so I can control that.
